### ISSUE TITLE
Support HMR of js files

### ISSUE THREAD

**Issue by Toilal** [ktsn/vue-template-loader#21]
Do you think it's possible to add support for HMR on component js/ts files ?

Currently it's the only real drawback remaining from this loader compared to vue-loader with `.vue` files.

**Comment by Toilal** [comment]
I'm quite new to webpack, but if I understand well, it should be possible by creating another loader (maybe a script-loader.js) for script files to add the hot reload code the same way it's done in [template-loader.js with writeHotReloadCode()](https://github.com/ktsn/vue-template-loader/blob/9faad83f198ae1c2633ecb4ea89598aa43515fed/lib/template-loader.js#L30-L32).

This new loader could be configured with a rule on *.js files.

**Comment by ktsn** [comment]
Thanks for thinking to improve this loader. But unfortunately, it's out of the scope of this loader. 
The main purpose of vue-template-loader is to compile a template and inject it to a component code  and it optionally deals with a style for convenience.

We can implement a new loader to hot reload for scripts, but I think it should be provided as other package such as vue-hot-reload-loader. So that the users can choose any hot reload loader they like.
