### ISSUE TITLE
Enable CompilerOptions.delimiters

### ISSUE THREAD

**Issue by ytkj** [ktsn/vue-template-loader#35]
`delimiters` option is described as "only available in the full build."
- https://vuejs.org/v2/api/#delimiters

But I want to use this option in runtime-only build vue.js library with vue-template-loader.

I think we can specify all the CompilerOptions to vue-template-compiler's `compiler.compile(template, [options])` like:
```
compiler.compile(templte, {delimiters: ['${', '}']});
```
- https://github.com/vuejs/vue/blob/dev/src/compiler/create-compiler.js#L34

So, would you please add `delimiters` option to vue-template-loader ?

**Comment by ktsn** [comment]
Why do you want to use the `delimiters` option in compile time?
To my understanding, it's the feature for avoiding to conflict with a server side template engine on runtime.

**Comment by ytkj** [comment]
In my product, I have a lot of document written in plain HTML. I want to migrate these HTML document to SPA. 

One problem:
Mustache '{{ }}' is used in many place to explain code snipet of AngularJS, Vue.js and so on.

Solution A:
Use delimiters option. only one place to change.

Solution B:
use v-pre directive. every code snipet to change.

> To my understanding, it's the feature for avoiding to conflict with a server side template engine on runtime.

You argument make sence, and I realize this might be a rare usecase. So, please close if you think this option is unnecessary. Thanks.

**Comment by ktsn** [comment]
Sorry, I totally forgot about this issue.
In my thought, as the official template compiler does not seems to be used in such use case, it should be avoided. I also think unifying the template format has an advantage (e.g. easy to implement static analyzing tools)

I think you should suggest about this in core vue repo at first 🙂 

Closing this issue for now because of the above, but I probably reopen if the official compiler support it.
